WebBanDienThoatBTL/Controllers/QuanLyNhaSanXuatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanDienThoatBTL.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;


namespace WebBanDienThoatBTL.Controllers
{
    public class QuanLyNhaSanXuatController : Controller
    {
        // GET: QuanLySanPham
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            return View(db.NhaSanXuats.ToList().OrderBy(n => n.MaNSX).ToPagedList(pageNumber, pageSize));
        }
        //Thêm mới điện thoại
        #region
        [HttpGet]
        public ActionResult ThemMoi()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(NhaSanXuat nsx, HttpPostedFileBase fileUpload)
        {
          
            db.NhaSanXuats.Add(nsx);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //Chỉnh sửa sản phẩm
        [HttpGet]
        public ActionResult ChinhSua(int MaNSX)
        {
            //Lấy ra điện thoại theo mã
            NhaSanXuat nsx = db.NhaSanXuats.SingleOrDefault(n => n.MaNSX == MaNSX);
            if (nsx == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(nsx);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(NhaSanXuat nsx, FormCollection f)
        {
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhập trong model
                db.Entry(nsx).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        //Hiển thị
        public ActionResult HienThi(int MaNSX)
        {
            //Lấy ra điện thoại theo mã
            NhaSanXuat nsx = db.NhaSanXuats.SingleOrDefault(n => n.MaNSX == MaNSX);
            if (nsx == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(nsx);
        }
        //Xóa sản phẩm
        [HttpGet]
        public ActionResult Xoa(int MaNSX)
        {
            //Lấy ra điện thoại theo mã
            NhaSanXuat nsx = db.NhaSanXuats.SingleOrDefault(n => n.MaNSX == MaNSX);
            if (nsx == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(nsx);
        }
        [HttpPost, ActionName("Xoa")]
        public ActionResult XacNhanXoa(int MaNSX)
        {
            NhaSanXuat nsx = db.NhaSanXuats.SingleOrDefault(n => n.MaNSX == MaNSX);
            if (nsx == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.NhaSanXuats.Remove(nsx);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion
    }
}

WebBanDienThoatBTL/Views/QuanLyNhaSanXuat/ChinhSua.cshtml
@model WebBanDienThoatBTL.Models.NhaSanXuat

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
<div>
    <i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;@Html.ActionLink("Quay Lại", "Index")
</div>
<h2>Chỉnh Sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <dl class="form-group">
            <dt>
                @Html.LabelFor(model => model.MaNSX, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>
            <dd class="col-md-10">
                @Html.TextBoxFor(model => model.MaNSX, new { style = "width: 206px; background:#EEEEEE; margin-left:5px;", disabled = "disabled" })
                @Html.Hidden("MaNSX", Model.MaNSX)
            </dd>
        </dl>

        <div class="form-group">
            @Html.LabelFor(model => model.TenNSX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNSX, new { htmlAttributes = new { style = "width: 206px; background:#FFF; margin-left:5px;" } })
                @Html.ValidationMessageFor(model => model.TenNSX, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { style = "width: 206px; background:#FFF; margin-left:5px;" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { style = "width: 206px; background:#FFF; margin-left:5px;" } })
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="margin-left: 40px;">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WebBanDienThoatBTL/Views/QuanLyNhaSanXuat/HienThi.cshtml
@model WebBanDienThoatBTL.Models.NhaSanXuat

@{
    ViewBag.Title = "HienThi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}


<i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;@Html.ActionLink("Quay Lại", "Index")


<h2>Chi Tiết Nhà Sản Xuất</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaNSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNSX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenNSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNSX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

    </dl>
</div>
<p>
    <i class="fa fa-cog" aria-hidden="true"></i>&nbsp;&nbsp;@Html.ActionLink("Sửa", "ChinhSua", new { @MaNSX = Model.MaNSX }) <br />
</p>

WebBanDienThoatBTL/Views/QuanLyNhaSanXuat/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.PagedList<WebBanDienThoatBTL.Models.NhaSanXuat>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    <i class="fa fa-plus" aria-hidden="true"></i>    @Html.ActionLink("Thêm Mới", "themmoi")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaNSX)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TenNSX)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DiaChi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DienThoai)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaNSX)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenNSX)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DiaChi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DienThoai)
        </td>
        <td>
            <a href="@Url.Action("HienThi","QuanLyNhaSanXuat", new { @MaNSX = item.MaNSX })">
                <i class="icon-eye-open"></i>
            </a>
            <a href="@Url.Action("ChinhSua","QuanLyNhaSanXuat", new { @MaNSX = item.MaNSX })">
                <i class="fa fa-cog" aria-hidden="true"></i>
            </a>
            <a href="@Url.Action("Xoa","QuanLyNhaSanXuat", new { @MaNSX = item.MaNSX })">
                <i class="fa fa-times" aria-hidden="true"></i>
            </a>
        </td>
    </tr>
}

</table>

WebBanDienThoatBTL/Views/QuanLyNhaSanXuat/ThemMoi.cshtml
@model WebBanDienThoatBTL.Models.NhaSanXuat

@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<div>
    <i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;@Html.ActionLink("Quay Lại", "Index")
</div>
<h2>Thêm Mới</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenNSX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNSX, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNSX, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WebBanDienThoatBTL/Views/QuanLyNhaSanXuat/Xoa.cshtml
@model WebBanDienThoatBTL.Models.NhaSanXuat

@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;@Html.ActionLink("Quay Lại", "Index")

<h2>Xóa</h2>

<h3>Bạn có muốn xóa thông tin?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaNSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNSX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenNSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNSX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="background-color: #ffffff; margin-left:10px">
            <input type="submit" value="Xóa" class="btn btn-default" />
        </div>
    }
</div>