WebBanDienThoatBTL/Controllers/QuanLySanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanDienThoatBTL.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;

namespace WebBanDienThoatBTL.Controllers
{
    public class QuanLySanPhamController : Controller
    {
        // GET: QuanLySanPham
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            return View(db.DienThoais.ToList().OrderBy(n=>n.MaDT).ToPagedList(pageNumber,pageSize));
        }
        //Thêm mới điện thoại
        #region
        [HttpGet]
        public ActionResult ThemMoi()
        {
            //Đưa dữ liệu vào dropdownList
            ViewBag.MaLDT = new SelectList(db.LoaiDienThoais.ToList().OrderBy(n=>n.TenLDT),"MaLDT","TenLDT");
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.ToList().OrderBy(n=>n.TenNSX),"MaNSX", "TenNSX");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(DienThoai dt, HttpPostedFileBase fileUpload)
        {
            ViewBag.MaLDT = new SelectList(db.LoaiDienThoais.ToList().OrderBy(n => n.TenLDT), "MaLDT", "TenLDT");
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.ToList().OrderBy(n => n.TenNSX), "MaNSX", "TenNSX");
            //Kiểm tra đường dẫn ảnh bìa
            if(fileUpload == null)
            {
                ViewBag.ThongBao = "Chọn hình ảnh!";
                return View();
            }
            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                //Lưu tên file
                var fileName = Path.GetFileName(fileUpload.FileName);
                //Lưu đường dẫn của file
                var path = Path.Combine(Server.MapPath("~/HinhAnhSP/"), fileName);
                //Kiểm tra tồn tại hình ảnh
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                dt.AnhBia = fileUpload.FileName;
                db.DienThoais.Add(dt);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        //Chỉnh sửa sản phẩm
        [HttpGet]
        public ActionResult ChinhSua(int MaDienThoai)
        {
            //Lấy ra điện thoại theo mã
            DienThoai dt = db.DienThoais.SingleOrDefault(n=>n.MaDT == MaDienThoai);
            if(dt == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.MaLDT = new SelectList(db.LoaiDienThoais.ToList().OrderBy(n => n.TenLDT), "MaLDT", "TenLDT",dt.MaLDT);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.ToList().OrderBy(n => n.TenNSX), "MaNSX", "TenNSX",dt.MaNSX);
            return View(dt);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(DienThoai dt, HttpPostedFileBase fileUpload)
        {
            ////Lấy dữ liệu từ textbox
            //trên , FormCollection f
            //DienThoai dt1 = db.DienThoais.SingleOrDefault(n => n.MaDT == dt.MaDT);
            //dt1.Mota = dt.Mota;
            //dt1.Mota = f.Get("abc").ToString();
            //db.SaveChanges();

            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhập trong model
                db.Entry(dt).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.MaLDT = new SelectList(db.LoaiDienThoais.ToList().OrderBy(n => n.TenLDT), "MaLDT", "TenLDT",dt.MaLDT);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.ToList().OrderBy(n => n.TenNSX), "MaNSX", "TenNSX",dt.MaNSX);
            return RedirectToAction("Index");
        }
        //Hiển thị
        public ActionResult HienThi(int MaDT)
        {
            //Lấy ra điện thoại theo mã
            DienThoai dt = db.DienThoais.SingleOrDefault(n => n.MaDT == MaDT);
            if (dt == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(dt);
        }
        //Xóa sản phẩm
        [HttpGet]
        public ActionResult Xoa(int MaDT)
        {
            //Lấy ra điện thoại theo mã
            DienThoai dt = db.DienThoais.SingleOrDefault(n => n.MaDT == MaDT);
            if (dt == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(dt);
        }
        [HttpPost, ActionName("Xoa")]
        public ActionResult XacNhanXoa(int MaDT)
        {
            DienThoai dt = db.DienThoais.SingleOrDefault(n => n.MaDT == MaDT);
            if (dt == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.DienThoais.Remove(dt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion
    }
}

WebBanDienThoatBTL/Views/QuanLySanPham/ChinhSua.cshtml
@model WebBanDienThoatBTL.Models.DienThoai

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<div>
    <i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;@Html.ActionLink("Quay Lại", "Index")
</div>
<h2>Chỉnh Sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Điện Thoại</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <dl class="form-group">
            <dt>
                @Html.LabelFor(model => model.MaDT, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>
            <dd class="col-md-10">
                @Html.TextBoxFor(model => model.MaDT, new { style = "width: 206px; background:#EEEEEE; margin-left:5px;", disabled = "disabled" })
                @Html.Hidden("MaDT", Model.MaDT)
            </dd>
        </dl>

        <div class="form-group">
            @Html.LabelFor(model => model.TenDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDT, new { htmlAttributes = new { style = "width: 206px; background:#FFF; margin-left:5px;" } })
                @Html.ValidationMessageFor(model => model.TenDT, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { style = "width: 206px; background:#FFF; margin-left:5px;" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<input type="file" name="fileUpload" />
                @ViewBag.ThongBao*@
                @Html.EditorFor(model => model.AnhBia, new { htmlAttributes = new { style = "width: 206px; background:#FFF; margin-left:5px;" } })
                @Html.ValidationMessageFor(model => model.AnhBia, "", new { @class = "text-danger" })
            </div>
        </div>

        <dl class="form-group">
            <dt>
                @Html.LabelFor(model => model.NgayCapNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>
            <dd class="col-md-10">
                @Html.TextBoxFor(model => model.NgayCapNhap, new { htmlAttributes = new { style = "width: 206px; background:#FFF; margin-left:5px;" } })
                @Html.ValidationMessageFor(model => model.NgayCapNhap, "", new { @class = "text-danger" })
            </dd>
        </dl>

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { style = "width: 206px; background:#FFF; margin-left:5px;" } })
                @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.MaLDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLDT")
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.MaNSX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNSX")
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Moi, new { htmlAttributes = new { style = "width: 206px; background:#FFF; margin-left:5px;" } })
                @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.Mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="Mota">@Model.Mota</textarea>
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WebBanDienThoatBTL/Views/QuanLySanPham/HienThi.cshtml
@model WebBanDienThoatBTL.Models.DienThoai

@{
    ViewBag.Title = "HienThi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;@Html.ActionLink("Quay Lại", "Index")

<h2>Chi Tiết Sản Phẩm</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mota)
        </dt>

        <dd>
            @Html.Raw(Model.Mota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            <img src="@Url.Content("~/HinhAnhSP/"+Model.AnhBia)" width="200" height="200" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiDienThoai.TenLDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiDienThoai.TenLDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaSanXuat.TenNSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaSanXuat.TenNSX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moi)
        </dd>

    </dl>
</div>
<p>
    <i class="fa fa-cog" aria-hidden="true"></i>&nbsp;&nbsp;@Html.ActionLink("Sửa", "ChinhSua", new { @MaDienThoai = Model.MaDT }) <br />
</p>

WebBanDienThoatBTL/Views/QuanLySanPham/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model PagedList.PagedList<WebBanDienThoatBTL.Models.DienThoai>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Danh Sách Điện Thoại</h2>

<p>
    <i class="fa fa-plus" aria-hidden="true"></i>    @Html.ActionLink("Thêm Mới", "ThemMoi")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TenDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GiaBan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Mota)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().AnhBia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NgayCapNhap)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().SoLuongTon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MaLDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MaNSX)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Moi)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaDT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TenDT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GiaBan)
        </td>
        <td>
            @Html.Raw(item.Mota)
        </td>
        <td>
            <div id="AnhMoTa"><img src="@Url.Content("~/HinhAnhSP/"+item.AnhBia)" width="200" height="200" /></div>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayCapNhap)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuongTon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoaiDienThoai.TenLDT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NhaSanXuat.TenNSX)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Moi)
        </td>
        <td>
            <a href="@Url.Action("HienThi","QuanLySanPham", new {@MaDT = item.MaDT})">
                <i class="icon-eye-open"></i>
            </a>
            <a href="@Url.Action("ChinhSua","QuanLySanPham", new {@MaDienThoai = item.MaDT})">
                <i class="fa fa-cog" aria-hidden="true"></i>
            </a>
            <a href="@Url.Action("Xoa","QuanLySanPham", new {@MaDT = item.MaDT})">
                <i class="fa fa-times" aria-hidden="true"></i>
            </a>
        </td>
    </tr>
}

</table>
@*Tạo linh liên kết của các trang*@
<div class="MenuTrang">
    <center>
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </center>
</div>
<style>
    .MenuTrang li {
        display: inline-block;
        justify-content: center;
    }
</style>

WebBanDienThoatBTL/Views/QuanLySanPham/ThemMoi.cshtml
@model WebBanDienThoatBTL.Models.DienThoai

@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
<div>
    <i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;@Html.ActionLink("Quay Lại", "Index")
</div>
<h2>Thêm mới dữ liệu</h2>
@*Thêm thuộc tính cho form để upload ảnh*@
@using(Html.BeginForm("ThemMoi","QuanLySanPham",FormMethod.Post, new { @enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Điện Thoại</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.TenDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenDT, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
            </div>
        </div>

        <dl class="form-group">
            <dt>
                @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>
            <dd class="col-md-10">
                <input type="file" name="fileUpload" />
                @*Thông báo trùng*@
                @ViewBag.ThongBao
            </dd>
        </dl>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayCapNhap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayCapNhap, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuongTon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuongTon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuongTon, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.MaLDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLDT")
                @Html.ValidationMessageFor(model => model.MaLDT, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.MaNSX, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNSX")
                @Html.ValidationMessageFor(model => model.MaNSX, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.Moi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Moi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Moi, "", new { @class = "text-danger" })
            </div>
        </div><br />

        <div class="form-group">
            @Html.LabelFor(model => model.Mota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="Mota"></textarea>
            </div>
        </div><br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WebBanDienThoatBTL/Views/QuanLySanPham/Xoa.cshtml
@model WebBanDienThoatBTL.Models.DienThoai

@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
<i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp;&nbsp;@Html.ActionLink("Quay Lại", "Index")
<h2>Xóa</h2>

<h3>Bạn muốn xóa?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mota)
        </dt>

        <dd>
            @Html.Raw(Model.Mota)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            <div id="AnhMoTa"><img src="@Url.Content("~/HinhAnhSP/"+Model.AnhBia)" width="200" height="200" /></div>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuongTon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuongTon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiDienThoai.TenLDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiDienThoai.TenLDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NhaSanXuat.TenNSX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NhaSanXuat.TenNSX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moi)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="background-color: #ffffff">
            <input type="submit" value="Xóa" class="btn btn-default" /> <br />
        </div>
    }
</div>