WebBanDienThoatBTL/Controllers/QuanLyDonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanDienThoatBTL.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;


namespace WebBanDienThoatBTL.Controllers
{
    public class QuanLyDonHangController : Controller
    {
        // GET: QuanLySanPham
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 10;
            return View(db.DonHangs.ToList().OrderBy(n => n.MaDonHang).ToPagedList(pageNumber, pageSize));
        }
        //Thêm mới điện thoại
        #region
        [HttpGet]
        public ActionResult ThemMoi()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(DonHang dh, HttpPostedFileBase fileUpload)
        {
            db.DonHangs.Add(dh);
            db.SaveChanges();
            return View();
        }
        //Chỉnh sửa sản phẩm
        [HttpGet]
        public ActionResult ChinhSua(int MaDonHang)
        {
            //Lấy ra điện thoại theo mã
            DonHang dh = db.DonHangs.SingleOrDefault(n => n.MaDonHang == MaDonHang);
            if (dh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(dh);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(DonHang dh, FormCollection f)
        {
            ////Lấy dữ liệu từ textbox
            //DienThoai dt1 = db.DienThoais.SingleOrDefault(n => n.MaDT == dt.MaDT);
            //dt1.Mota = dt.Mota;
            //dt1.Mota = f.Get("abc").ToString();
            //db.SaveChanges();

            //Thêm vào cơ sở dữ liệu
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhập trong model
                db.Entry(dh).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
        //Hiển thị
        public ActionResult HienThi(int MaDonHangChiTiet)
        {
            //Lấy ra chi tiết đơn hàng theo mã
            //DonHang dh = db.DonHangs.SingleOrDefault(n => n.MaDonHang == MaDonHang);
            //ChiTietDonHang ctdh = db.ChiTietDonHangs.ToList().OrderBy(n=>n.MaDonHang == MaDonHangChiTiet);
            //if (ctdh == null)
            //{
            //    Response.StatusCode = 404;
            //    return null;
            //}
            return View(db.ChiTietDonHangs.ToList().OrderBy(n=>n.MaDonHang).Where(n=>n.MaDonHang==MaDonHangChiTiet));
        }
        //Xóa sản phẩm
        [HttpGet]
        public ActionResult Xoa(int MaDonHang)
        {
            //Lấy ra điện thoại theo mã
            DonHang dh = db.DonHangs.SingleOrDefault(n => n.MaDonHang == MaDonHang);
            if (dh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(dh);
        }
        [HttpPost, ActionName("Xoa")]
        public ActionResult XacNhanXoa(int MaDonHang)
        {
            DonHang dh = db.DonHangs.SingleOrDefault(n => n.MaDonHang == MaDonHang);
            if (dh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.DonHangs.Remove(dh);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion
    }
}

WebBanDienThoatBTL/Views/QuanLyDonHang/ChinhSua.cshtml
@model WebBanDienThoatBTL.Models.DonHang

@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
<div>
    <i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp;@Html.ActionLink("Quay Lại", "Index")
</div>
<h2>Sửa Đơn Hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <dl class="form-group">
            <dt>
                @Html.LabelFor(model => model.MaDonHang, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>
            <dd class="col-md-10">
                @Html.TextBoxFor(model => model.MaDonHang, new { style = "width: 206px; background:#EEEEEE; margin-left:5px;", disabled = "disabled"})
                @*<span style="font-size:15px; margin-top:2px; margin-left: 5px">@Model.MaDonHang</span>*@
                @Html.Hidden("MaDonHang", Model.MaDonHang)
            </dd>
        </dl>

        <div class="form-group">
            @Html.LabelFor(model => model.DaThanhToan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DaThanhToan, new { style = "width: 206px; background:#FFF; margin-left:5px;" })
                @Html.ValidationMessageFor(model => model.DaThanhToan, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.TinhTrangGiaoHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TinhTrangGiaoHang, new { style = "width: 206px; background:#FFF; margin-left:5px;" })
                @Html.ValidationMessageFor(model => model.TinhTrangGiaoHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <dl class="form-group">
            <dt>
                @Html.LabelFor(model => model.NgayDat, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>
            <dd class="col-md-10">
                @Html.TextBoxFor(model => model.NgayDat, new { style = "width: 206px; background:#EEEEEE; margin-left:5px;", disabled = "disabled" })
                @*<span style="font-size:15px; margin-top:2px; margin-left: 5px">@Model.NgayDat</span>*@
                @Html.Hidden("NgayDat", Model.NgayDat)
            </dd>
        </dl>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayGiao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiao, new { style = "width: 206px; background:#FFF; margin-left:5px;" })
                @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <dl class="form-group">
            <dt>
                @Html.LabelFor(model => model.MaKH, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>
            <dd class="col-md-10">
                @Html.TextBoxFor(model => model.KhachHang.HoTen, new { style = "width: 206px; background:#EEEEEE; margin-left:5px;", disabled = "disabled" })
                @*<span style="font-size:15px; margin-top:2px; margin-left: 5px">@Model.KhachHang.HoTen</span>*@
                @Html.Hidden("MaKH", Model.MaKH)
            </dd>
        </dl>

        <dl class="form-group">
            <dt>
                @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>
            <dd class="col-md-10">
                @Html.TextBoxFor(model => model.DiaChi, new { style = "width: 206px; background:#EEEEEE; margin-left:5px;", disabled = "disabled" })
                @*<span style="font-size:15px; margin-top:2px; margin-left: 5px">@Model.DiaChi</span>*@
                @Html.Hidden("DiaChi", Model.DiaChi)
            </dd>
        </dl>

        <dl class="form-group">
            <dt>
                @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
            </dt>
            <dd class="col-md-10">
                @Html.TextBoxFor(model => model.DienThoai, new { style = "width: 206px; background:#EEEEEE; margin-left:5px;", disabled = "disabled" })
                @*<span style="font-size:15px; margin-top:2px; margin-left: 5px">@Model.DienThoai</span>*@
                @Html.Hidden("DienThoai", Model.DienThoai)
            </dd>
        </dl>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WebBanDienThoatBTL/Views/QuanLyDonHang/HienThi.cshtml
@model IEnumerable<WebBanDienThoatBTL.Models.ChiTietDonHang>

@{
    ViewBag.Title = "HienThi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}
<div>
    <i class="fa fa-arrow-left" aria-hidden="true"></i> &nbsp;@Html.ActionLink("Quay Lại", "Index")
</div>
<h2>Chi Tiết Đơn Hàng</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.MaDonHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MaDT)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SoLuong)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DonGia)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaDonHang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DienThoai.TenDT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoLuong)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DonGia)
        </td>
    </tr>
}

</table>

WebBanDienThoatBTL/Views/QuanLyDonHang/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@using System.Web.Mvc;
@using WebBanDienThoatBTL.Models;
@model PagedList.PagedList<DonHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Danh Sách Đơn Hàng</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().MaDonHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DaThanhToan)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TinhTrangGiaoHang)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NgayDat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NgayGiao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MaKH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DiaChi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DienThoai)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaDonHang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DaThanhToan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TinhTrangGiaoHang)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayDat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayGiao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KhachHang.HoTen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DiaChi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DienThoai)
        </td>
        <td>
            <a href="@Url.Action("HienThi","QuanLyDonHang", new { @MaDonHangChiTiet = item.MaDonHang})">
                <i class="icon-eye-open"></i>
            </a>
            <a href="@Url.Action("ChinhSua","QuanLyDonHang", new { @MaDonHang = item.MaDonHang })">
                <i class="fa fa-cog" aria-hidden="true"></i>
            </a>
        </td>
    </tr>
}

</table>

WebBanDienThoatBTL/Views/QuanLyDonHang/Xoa.cshtml
@model WebBanDienThoatBTL.Models.DonHang

@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<h2>Xoa</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DonHang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaDonHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaDonHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DaThanhToan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaThanhToan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TinhTrangGiaoHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TinhTrangGiaoHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayDat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayGiao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayGiao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>